name: poltype
channels:
  - conda-forge
  - psi4
dependencies:
  - python=3.7
  - git
  - matplotlib=3.4.3
  - pip=21.3.1
  - scipy=1.7.1
  - cairosvg=2.5.2
  - mdanalysis=2.0.0
  - openbabel=2.4.1
  - svgutils=0.3.4
  - psi4=1.3.2+ecbda83
  - rdkit=2021.09.2
  - psutil=5.7.2
